# 使用语言
language: node_js
# node版本
node_js:
  - 12
# 设置只监听哪个分支
branches:
  only:
    - hexo  
# 缓存，可以节省集成的时间，这里我用了yarn，如果不用可以删除
cache:
  apt: true
  yarn: true
  directories:
    - node_modules
# tarvis生命周期执行顺序详见官网文档
before_install:
- git config --global user.name "Caffreyfans"
- git config --global user.email "Caffreyfans@163.com"
- npm install -g hexo-cli
install:
# 不用yarn的话这里改成 npm i 即可
- npm i
script:
- hexo clean
- hexo generate
after_success:
- cd ./public
- git init
- git add .
- git commit -m "Travis CI Auto Builder"
- git push --quiet --force https://$REPO_TOKEN@github.com/Caffreyfans/Caffreyfans.github.io.git
  master